- name: daemon reload
  hosts: mytyltyl
  tasks:
    - name: git pull
      git:
        repo: https://github.com/yuchiki/mytyltyl-server.git
        dest: /tmp/mytyltyl-server
      register: mytyltyl_code
    - name: build
      make:
        chdir: /tmp/mytyltyl-server
        target: build
        environment:
          RELEASE_VERSION: "{{ release_version }}"
      when: mytyltyl_code.changed
    - name: copy to /usr/local/bin/mytyltyl-server
      copy:
        src: /tmp/mytyltyl-server/out
        dest: /usr/local/bin/mytyltyl-server
        remote_src: yes
        unsafe_writes: true
      become: yes
    - name: restart mytyltyl
      systemd:
        name: mytyltyl.service
        state: restarted
        enabled: true
      when: mytyltyl_code.changed
      become: yes
