- name: daemon reload
  hosts: mytyltyl
  tasks:
    - name: git pull
      git:
        repo: https://github.com/yuchiki/mytyltyl-server.git
        dest: ~/mytyltyl-server
    - name: build
      make:
        chdir: ~/mytyltyl-server
        target: build
    - name: copy to /usr/local/bin/mytyltyl-server
      copy:
        src: ~/mytyltyl-server/out
        dest: /usr/local/bin/mytyltyl-server
        remote_src: yes
        unsafe_writes: true
    - name: start mytyltyl
      systemd:
        name: mytyltyl.service
        state: restarted
        enabled: true
