on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy with ansible playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy-mytyltyl-server.yaml
          directory: ./ansible
          key: ${{secrets.MYTYLTYL_PEM}}
          options: |
            --inventory ./ansible/inventory
