on:
  release:
    types: [published]
jobs:
  release-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"
      - name: install dependencies
        run: |
          dotnet restore
      - name: build
        run: |
          dotnet build
      - name: test
        run: |
          dotnet test
      - name: pack
        run: |
          dotnet pack mytyltyl-api -o mytyltyl-api-out
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
      - name: Publish API to Nuget
        run: |
          dotnet nuget push "mytyltyl-api-out/*.nupkg" --api-key ${{secrets.NUGET_YUCHIKI_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
